use_frameworks!

target 'VidaliciousFakebookObjC_Example' do
  pod 'VidaliciousFakebookObjC', :path => '../'

  target 'VidaliciousFakebookObjC_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
